// src/services/firebase.js

import { initializeApp } from "firebase/app"; // Core Firebase app initializer
import { getFirestore } from "firebase/firestore"; // Firestore database service
import { getAuth } from "firebase/auth"; // Firebase Authentication service

// Firebase configuration object (replace with your actual config values)
const firebaseConfig = {
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY, // API key from Firebase project settings
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN, // e.g., your-app.firebaseapp.com
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID, // Firebase project ID
  storageBucket: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET, // Cloud storage bucket
  messagingSenderId: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID, // Messaging sender ID (for FCM, if used)
  appId: process.env.REACT_APP_FIREBASE_APP_ID, // App ID generated by Firebase
};

// Initialize the Firebase app with the provided config
const app = initializeApp(firebaseConfig);

// Initialize Firestore (for database operations)
export const db = getFirestore(app);

// Initialize Firebase Authentication (for anonymous or custom login)
export const auth = getAuth(app);
